IF EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'ID'
          AND Object_ID = Object_ID(N'SK_F2_FLUSSI.F2_T_EXP_TAGETIK_MOV'))
BEGIN
    ALTER TABLE SK_F2_FLUSSI.F2_T_EXP_TAGETIK_MOV
    DROP COLUMN ID
END

ALTER TABLE SK_F2_FLUSSI.F2_T_EXP_TAGETIK_MOV
   ADD ID INT IDENTITY
	 CONSTRAINT PK_F2_T_EXP_TAGETIK_MOV PRIMARY KEY CLUSTERED